### ISSUE TITLE
Is the update.ini file required?

### ISSUE THREAD

**Issue by Hackmodford** [VisualAppeal/PHP-Auto-Update#10]
Did you switch to using a json file to keep track of available updates?

**Comment by thelfensdrfer** [comment]
Yeah, please see the new readme for details, aspecially this part: https://github.com/VisualAppeal/PHP-Auto-Update#server

The ini format is still available. You only have to specify the absolute url to the file `$update->setUpdateFile($url)` and the library tries to guess what format it is (https://github.com/VisualAppeal/PHP-Auto-Update/blob/master/src/AutoUpdate.php#L354-L376).
