### ISSUE TITLE
AutoUpdate.php Line 338 Error

### ISSUE THREAD

**Issue by Hackmodford** [VisualAppeal/PHP-Auto-Update#11]
I'm testing the new version and I get this error.
```
PHP Parse error:  syntax error, unexpected '[' in C:\inetpub\wwwroot\mamobile_test\vendor\visualappeal\php-auto-update\src\AutoUpdate.php on line 338
```

**Comment by Hackmodford** [comment]
Is this because I'm using PHP 5.3?

**Comment by thelfensdrfer** [comment]
I was going to write exactly the same;) Yeah, this is because of the new array syntax introduced in php 5.4. The end of life for 5.3 was announced in august 2014 so there will be no more bugfixes, see http://de2.php.net/archive/2014.php#id2014-08-14-1
