### ISSUE TITLE
Update database ?

### ISSUE THREAD

**Issue by nubox** [VisualAppeal/PHP-Auto-Update#17]
Hello,
how to update the database at the same time as the update?
Thanks.

**Comment by thelfensdrfer** [comment]
Hi,

there is a public variable "updateScriptName". If you include a php file in your zip file with the name stored in in "updateScriptName", it will be automatically required by the update class. There you can insert any database logic for this update. 

I do not plan to include database migrations at the moment. But feel free to add them if you need to and submit a pull request;)
