### ISSUE TITLE
Update failed: 70!

### ISSUE THREAD

**Issue by shahmarasy** [VisualAppeal/PHP-Auto-Update#18]
i have problem
#1 what is this error
```

Notice: Undefined variable: zip in C:\xampp\htdocs\PHP-Auto-Update-master\updater\src\AutoUpdate.php on line 694

Warning: zip_close() expects parameter 1 to be resource, null given in C:\xampp\htdocs\PHP-Auto-Update-master\updater\src\AutoUpdate.php on line 694
Update failed: 70!

array(32) {
  [0]=>
  array(3) {
    ["filename"]=>
    string(6) "files/"
    ["foldername"]=>
    string(66) "C:\xampp\htdocs\PHP-Auto-Update-master\example\client\update/..//."
    ["absolute_filename"]=>
    string(71) "C:\xampp\htdocs\PHP-Auto-Update-master\example\client\update/..//files/"
  }
```
#2 
how can use this code in codeigniter or other frameworks

**Comment by MTRNord** [comment]
I am not sure but it seems like that the PHP code is not working on your Windows XAMPP Server because of the direction of the Slash. That could be one thing that makes trouble here.

**Comment by Demonslay335** [comment]
That line looks like it may have a bug. `$zip` is being called before it can be defined, thus the "undefined variable" notice. Since the variable is not defined, it is a `NULL` value, which crashes the `zip_close()` function.

https://github.com/VisualAppeal/PHP-Auto-Update/blob/master/src/AutoUpdate.php#L694

**Comment by thelfensdrfer** [comment]
Yeah, this is a bug which occurs only if the simulation of the update fails (so there is another problem). I will fix that today and replace all occurances of `/` with `DIRECTORY_SEPARATOR`. But I don't think this should be a problem. As far as I know, PHP replaces the slashes anyway with the right ones for the platform it is running on.

**Comment by thelfensdrfer** [comment]
To number 2: I would say it depends on the framework you are using. I never worked with codeigniter but you can

a) Include normal PHP files in every framework or
b) Create some kind of extension or plugin which is possible in the frameworks I know so far.
