### ISSUE TITLE
PHP Requirement

### ISSUE THREAD

**Issue by parkerj** [VisualAppeal/PHP-Auto-Update#19]
Can you tell me why PHP 5.4 is no longer supported? Did you add something that is only supported in PHP 5.5+?

**Comment by thelfensdrfer** [comment]
I don't think so. Just raised the version requirement since 5.4 (and actually 5.5 too) is not officially supported anymore http://php.net/supported-versions.php

**Comment by parkerj** [comment]
Got it, you are applying EOL to PHP versions.

**Comment by thelfensdrfer** [comment]
If you replace "you" with "The PHP Group", yes.
