### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by unclesamwk** [VisualAppeal/PHP-Auto-Update#20]
Hello,

cool project :-)

But i have any questions. Can you help me?

I make the Server/client config und the update file to update, but it seems like SIMULATE.

[2016-10-17 15:10:56] auto-update.DEBUG: Latest update downloaded to "/html/cms/temp/0.2.0.zip" [] []
[2016-10-17 15:10:56] auto-update.NOTICE: Trying to install update "/html/cms/temp/0.2.0.zip" [] []
[2016-10-17 15:10:56] auto-update.NOTICE: [SIMULATE] Install new version [] []
[2016-10-17 15:10:56] auto-update.NOTICE: Update "0.2.0" successfully installed [] []
[2016-10-17 15:10:56] auto-update.DEBUG: Trying to delete update file "/html/cms/temp/0.2.0.zip" after successfull update [] []
[2016-10-17 15:10:56] auto-update.INFO: Update file "/html/cms/temp/0.2.0.zip" deleted after successfull update [] []

Where kann i set run a LIVE Update?
Where set the Version change after Update?

greetings Sam

**Comment by thelfensdrfer** [comment]
The `update` method has two arguments, with the first one you can define if the update should be simulated. So you have to set it to `false` (`true` is the default value).

You can set the new version if the update was successful. A successful update returns true when you call the `update` method.

**Comment by unclesamwk** [comment]
Hey,

Danke für die Antwort. Ich nutze dass so:

<?php

require(__DIR__ . '/vendor/autoload.php');

use \VisualAppeal\AutoUpdate;

$update = new AutoUpdate(__DIR__ . '/temp', __DIR__ . '/../', 60);
$update->setCurrentVersion('0.1.0');
$update->setUpdateUrl('xxxxxxx'); //Replace with your server update directory

// Optional:
$update->addLogHandler(new Monolog\Handler\StreamHandler(__DIR__ . '/update.log'));
$update->setCache(new Desarrolla2\Cache\Adapter\File(__DIR__ . '/cache'), 3600);

//Check for a new update
if ($update->checkUpdate() === false)
        die('Could not check for updates! See log file for details.');

if ($update->newVersionAvailable()) {
        //Install new update
        echo 'New Version: ' . $update->getLatestVersion() . '<br>';
        echo 'Installing Updates: <br>';
        echo '<pre>';
        var_dump(array_map(function($version) {
                return (string) $version;
        }, $update->getVersionsToUpdate()));
        echo '</pre>';

        $result = $update->update();
        if ($result === true) {
                echo 'Update successful<br>';
        } else {
                echo 'Update failed: ' . $result . '!<br>';

                if ($result = AutoUpdate::ERROR_SIMULATE) {
                        echo '<pre>';
                        var_dump($update->getSimulationResults());
                        echo '</pre>';
                }
        }
} else {
        echo 'Current Version is up to date<br>';
}

echo 'Log:<br>';
echo nl2br(file_get_contents(__DIR__ . '/update.log'));




Kannst Du mir bitte sagen an welcher Stelle ich das anpassen muss?

**Comment by thelfensdrfer** [comment]
You have to change line `$result = $update->update();` to `$result = $update->update(false);` to set the "simulate" argument to false.

In the next line the script checks if the update was successful and prints the message "Update successful". You can replace that with whatever you like.

**Comment by unclesamwk** [comment]
Thank you. It works perfect. 
Can you Update the README please.

**Comment by thelfensdrfer** [comment]
https://github.com/VisualAppeal/PHP-Auto-Update/commit/d9e9d13ca3debfb44610b270f280e29d98736cd9

:+1:
