### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dotdotfx** [VisualAppeal/PHP-Auto-Update#21]
Hi,

thanks for this library, really useful and intuitive! Are you planning to add a new release anytime soon? I'm currently using the git-master as a dependency in composer because of the fixes applied after 0.9.2 (see #18 ). This messes up my CI workflow, since `composer install` also creates `.git/` directories which I then have to exclude from the artifact … etc. Would really appreciate a new release version 👍 😃

**Comment by thelfensdrfer** [comment]
Hi, I will release a next version in the next 2 days!

**Comment by dotdotfx** [comment]
Great, thanks a lot!

**Comment by thelfensdrfer** [comment]
https://github.com/VisualAppeal/PHP-Auto-Update/tree/0.9.3
