### ISSUE TITLE
Invalid argument supplied for foreach() on line: 484

### ISSUE THREAD

**Issue by ttimot24** [VisualAppeal/PHP-Auto-Update#22]
I got this exception why does it happens? : Invalid argument supplied for foreach() on line: 484 in .. src/AutoUpdate.php

The url I added is correct surely. And I copied your update.json.

**Comment by ttimot24** [comment]
Okey I found 2 problem in your code:

on line 431 : if ($versions === false) should be if ($versions === null) 

on line 433:  $this->_updateUrl .DIRECTORY_SEPARATOR. $this->_updateFile should be  $this->_updateUrl . "/" . $this->_updateFile

**Comment by thelfensdrfer** [comment]
Thanks for the fix!
