### ISSUE TITLE
subdirs created as files, touch throws exception.

### ISSUE THREAD

**Issue by ttimot24** [VisualAppeal/PHP-Auto-Update#24]
Hi!

All the subdirs are created as files. And after that touch throws invalid argument exception.
Also is_dir returns false on subdirs.

I'm trieing on windows with xampp. I know that on linux folders are files too. Maybe this is the problem? I'll check it on linux later.

Can you please fix these problems? Thanx!

**Comment by thelfensdrfer** [comment]
Are you sure? In my tests, all directories and subdirectories were created as such.

**Comment by ttimot24** [comment]
Yeah, I'm using your example code with this update file: 
[http://www.eterfesztival.hu/hcms_online_store/updates/update.json](http://www.eterfesztival.hu/hcms_online_store/updates/update.json)

(Only the 1.0.0-alpha zip is on the server, so please set the version to 0.9.5 at least)

**Comment by thelfensdrfer** [comment]
I can't confirm your problem. I added a few subdirectories to the test version 0.2.1 and the zip file got extracted like it was created, with subdirectories. I think this may be a windows problem but I can't test it on windows at the moment.

**Comment by ttimot24** [comment]
I managed to update succesfully on CentOS so it looks like it's a windows specific problem.  But along the many many tests I found another bug. If one of the files is empty, in the zip, the update will fail. I know there's no much sense to a file beeing empty in an update, just mention that.

**Comment by thelfensdrfer** [comment]
No this could definitly be possible. I will look into that #26.
