### ISSUE TITLE
Can't install new file if file is empty

### ISSUE THREAD

**Issue by thelfensdrfer** [VisualAppeal/PHP-Auto-Update#26]

**Comment by ttimot24** [comment]
I guess touch should be changed to file_put_contents. Every OS saves the modification time for a file. And it's not for creating a file. What do you think?

**Comment by thelfensdrfer** [comment]
`touch` is used (and should be os independent), so `fwrite` could be used whether the file existed or not. And according to the [file_put_content](https://secure.php.net/manual/en/function.file-put-contents.php) docs, it's just a wrapper for `fwrite` anyways.
