### ISSUE TITLE
Monolog Dependency

### ISSUE THREAD

**Issue by parkerj** [VisualAppeal/PHP-Auto-Update#27]
I am currently using Monolog 1.22.*, but PHP Auto Update requires 1.21.*

Is there something in 1.22.* that is not supported in the latest release of PHP Auto Update?

Error Message:
`- visualappeal/php-auto-update 0.9.4 requires monolog/monolog 1.21.* -> satisfiable by monolog/monolog[1.21.0] but these conflict with your requirements or minimum-stability.`

**Comment by thelfensdrfer** [comment]
Not that I know of, but it's only tested with 1.21. Can you change it locally and test if it works with 1.22?

**Comment by parkerj** [comment]
Ok, so I am using Monolog Cascade with also installs v1.22.0 of Monolog. I've tested it, and I haven't run into any errors or issues.

**Comment by parkerj** [comment]
Bringing this back up again, since when using composer to update, Monolog gets downgraded back to 1.21.x from 1.22.x in the latest version of PHP Auto Update.
