### ISSUE TITLE
contact stablehost to update to php to 5.6 , 7.0

### ISSUE THREAD

**Issue by MohiniSea** [VisualAppeal/PHP-Auto-Update#36]
Hi,

For security reasons and an increase in speed I want to update the PHP version of my WordPress website to PHP 7. WordPress also strongly recommends the latest version of PHP on their requirements page, https://wordpress.org/about/requirements/.

More information about currently supported versions of PHP can be found here: http://php.net/supported-versions.php.

I've heard that sometimes a website can break when updating the PHP version. Can you assist me and update my site safely to PHP 7?

Thanks!

**Comment by thelfensdrfer** [comment]
This library is about updating an application, not your server (or the provided software). If you have questions you can mail me at tim@visualappeal.de.
