### ISSUE TITLE
Double slashes?

### ISSUE THREAD

**Issue by Guilddrive** [VisualAppeal/PHP-Auto-Update#38]
When checking the update logs, I noticed that appears with each entry a double slash? 
`Get new updates from https://update.server.de/folder//modul/update.json [] []`
Furthermore, I always get the error "File not found" with Windows Server and everything works fine on Linux. Would be very grateful for an advice. Best regards, Daniel

**Comment by thelfensdrfer** [comment]
You just have to set `https://update.server.de/folder` instead `https://update.server.de/folder/` as your update url.
