### ISSUE TITLE
CURLOPT_SSL_VERIFYHOST

### ISSUE THREAD

**Issue by whoami213** [VisualAppeal/PHP-Auto-Update#45]
Notice: curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in C:\xampp\htdocs\xx\xxx\xxx\vendor\visualappeal\php-auto-update\src\AutoUpdate.php on line 590

**Comment by thelfensdrfer** [comment]
Thanks!
