### ISSUE TITLE
Dynamic currentVersion

### ISSUE THREAD

**Issue by lucasbceo** [VisualAppeal/PHP-Auto-Update#5]
Hello,

The currentVersion variable in index.php (client side) should be dynamic, and change when the update is complete

index.php code in question:
$update->currentVersion = 1;

It's a static field, if I update my code to Version 2, I have to change this value manually, wich kills the purpose of an automated PHP system

Thanks

**Comment by thelfensdrfer** [comment]
You can do this like tikky suggested or you get the current version from another file which will be updated like:

```php
<?php

return '1.4.12';
```

```php
$update->currentVersion = require(__DIR__ . '/currentversion.php');
```

or you get the version from a database and update the database after a sucessfull update.
