### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by demortx** [VisualAppeal/PHP-Auto-Update#51]
https://github.com/VisualAppeal/PHP-Auto-Update/blob/06394df0bbd5fc7d398f591f4602e16c8239aaa0/src/AutoUpdate.php#L809

$fileStats['filename'] -> $fileStats['name']

https://github.com/VisualAppeal/PHP-Auto-Update/blob/06394df0bbd5fc7d398f591f4602e16c8239aaa0/src/AutoUpdate.php#L812

, $this->installDir . $filename); -> , $this->installDir);

https://github.com/VisualAppeal/PHP-Auto-Update/blob/06394df0bbd5fc7d398f591f4602e16c8239aaa0/src/AutoUpdate.php#L827

$fileStats['filename'] -> $fileStats['name']

**Comment by thelfensdrfer** [comment]
Thanks for your feedback! Are you sure about the changes? I tried it with the example in the example folder and all files and directories get extracted without errors to the correct place.

**Comment by demortx** [comment]
This error appears when we turn off the simulation and go into live mode, and if you look at the code, there is no $ fileStats ['filename'] variable
